### ISSUE TITLE
Design GPT prompts [TODO]

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/chatify#3]
# Design GPT prompts

How should ChatGPT be prompted to generate its explanations?

# Completion criteria

Save text files to a "prompts" folder with each of the following prompts:
- [ ] equation
- [ ] plain text
- [x] code

# Discussion points and unknowns (optional)

- Which version of ChatGPT should we be using?  This may be constrained in part by budget requirements.
- Should there be different "levels" or "contexts" for each prompt?  E.g., what other materials should be included in the prompt, what information should be included about the intended audience, etc.?
- What's the right "tone" for the explainer?  Do we want this to be adjustable?  E.g., should it be professional?  Humorous?  Fun?  Efficient?

**Comment by jeremyforest** [comment]
Potential ressources  to design the best prompts: 
- https://prompts.chat/

**Comment by Neural-Hacker** [comment]
I've looked everywhere for the button to assign myself to this issue

**Comment by AGuyNextDoor** [comment]
The github link to the complete prompt : https://github.com/JushBJJ/Mr.-Ranedeer-AI-Tutor/blob/main/Mr_Ranedeer.json

**Comment by Helena-Yuhan-Liu** [comment]
@Neural-Hacker, how would you like to divide up the task for designing the prompts? 

One possibility is that one of us could take care of the markdown cells (text + equations) and the other could take care of the coding cells. 

The other is to divide between user contexts (level, major, length/depth of explanation, tone, or other choices included in the comment above). 

I am happy to pursue other possibilities too. It would be appreciated if you could please let me know your thoughts.

**Comment by Helena-Yuhan-Liu** [comment]
Hi @Neural-Hacker, your plan sounds great to me. Would you be available between 10:30am to 3pm ET tomorrow or anytime Monday after 10:30am ET? Thanks!

**Comment by Neural-Hacker** [comment]
Hi @Helena-Yuhan-Liu Monday at 10:30am works for me.

**Comment by Helena-Yuhan-Liu** [comment]
Hi @Neural-Hacker, sounds good. I just sent you an Outlook invite with a Zoom link.

**Comment by jeremymanning** [comment]
Potential prompt approach: "depths of explanation"

Rather than organizing prompts around the "level" of the learner, we could instead use different prompts to provide different depths of explanation.  For example:

- Level 1: describe (at a high level) what the code block is "about" without providing clues about how to approach the given problem
- Level 2: give some high-level hints about how to solve the given problem or fill in missing code
- Level 3: give specific "pseudocode" hints (but without providing an exact solution) to help solve the problem
- Level 4: provide a complete solution along with explanations
