### ISSUE TITLE
Chatify asks for user response

### ISSUE THREAD

**Issue by jrudoler** [ContextLab/chatify#47]
**Describe the bug**
Chatify politely asks for the user to clarify what it can help debug, but as far as I can tell it is not possible to interact with the LLM in a back-and-forth chat (the widget has no text entry / chat box, at least).

**To Reproduce**
1. Go to [this tutorial notebook](https://colab.research.google.com/github/ContextLab/course-content/blob/main/tutorials/W1D5_DeepLearning/student/W1D5_Tutorial4.ipynb)
3. Scroll down Section 1: Decoding - Investigating model and evaluating performance. Expand the third cell in this section, which should start with `# @markdown Execute this cell to train the network` and then defines the `DeepNetReLU` class.
4. Add some syntactical bug to the cell - e.g. delete a colon in the first line of the training loop. Or don't add any bugs - the behavior is still not expected.
5. Add the %%explain magic to the top of the cell and run it - then from the dropdown in the Robo-tutor tab, select "get help with debugging" and hit "Submit request"

**Expected behavior**
I expected the Robo-tutor to give me a concrete response, either pointing out a problematic line of code or claiming that the code is error-free. 

**Screenshots**
<img width="1056" alt="Screenshot 2023-08-09 at 2 06 35 PM" src="https://github.com/ContextLab/chatify/assets/40604402/41d33381-980a-4c14-b99c-ecc3a790ac56">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.4.1
 - Browser: Safari
 - Version: 16.5.2

**Comment by jrudoler** [comment]
Yep, it's still producing the same error for me (after starting from scratch multiple times):

<img width="1260" alt="Screenshot 2023-08-10 at 2 42 36 PM" src="https://github.com/ContextLab/chatify/assets/40604402/3c508010-4ab2-432f-81f1-65b279304d0d">

I often get some variation of "What's the issue?" or "What seems to be the problem?".

By repeatedly clicking "submit request" I can get it to actually produce a response catching the bug sometimes:

<img width="1205" alt="Screenshot 2023-08-10 at 2 47 45 PM" src="https://github.com/ContextLab/chatify/assets/40604402/72eede99-22c7-4f8f-9f89-4aecaea92c94">

My sample size is small, but the error came up probably 4/5 times.

**Comment by HemuManju** [comment]
So the response discrepancy seems to stem from the GPT side, which we cannot directly control. Nonetheless, we will keep this in mind while updating the prompts in future release. I will close this for now.
