### ISSUE TITLE
Button (menu?) adder code [TODO]

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/chatify#5]
# Overview

We need to figure out how to add a button, menu, etc. to an iPython notebook cell where the appropriate magic command has been called.

Suggested input:
  - Text from an iPython notebook cell

Suggested output:
  - The rendered version of the cell

# Completion criteria

- [ ] look into how this might be done and write a set of tasks/issues

# Resources (optional)

- iPywidgets seems likely to be the "right" way to do this: [[link](https://ipywidgets.readthedocs.io/en/stable/)]
- This stackoverflow post seems relevant too: [[link](https://stackoverflow.com/questions/74142313/jupyter-notebook-renders-text-instead-of-ipywidgets)

# Discussion points and unknowns (optional)

I don't fully understand how "rendering" works in iPython notebooks.  E.g., what happens between (a) when the user selects the cell type (e.g., a "Markdown cell"), enters text (i.e., the contents of the markdown cell), and then runs the cell with Shift + Enter and (b) when the cell contents gets rendered in the browser window.  It seems like we need to "intercept" the text/code someone enters into a cell before that final rendered output is generated.

**Comment by dherrera1911** [comment]
I will look at what is involved in 'intercepting' the cell contents, at a high level. What I understood is that we want to take the content written into a cell (either code or text), and intercept it so that we can use that as input to the chatify function. I will aim to suggest some task/issue early next week.

**Comment by HemuManju** [comment]
Hello @dherrera1911, I believe the discussion is about parsing the cell contents. However, IPython can already parse the cell content and pass as string (https://ipython.readthedocs.io/en/stable/config/custommagics.html). 

Regarding the button, I think we can take two options: 

1. Write a Jupyter lab (or IPython) extension using Tyscript or Javascript.
2. Write an IPython widget and integrate it with magic commands.

**Comment by dherrera1911** [comment]
Thanks. Didn't have time to look into that before vacation at the end, but it sounds from this that it's not much needed then.
